[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "yolov10"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
req = "uv pip install determined==0.32.1 -i https://mirrors.aliyun.com/pypi/simple/"


[dependencies]
ultralytics = ">=8.3.21,<9"
pip = ">=24.2,<25"
nccl = ">=2.23.4.1,<3"
mpi = ">=1.0.1,<2"
pyarrow = ">=18.1.0,<19"
tenacity = ">=9.0.0,<10"
